# Generated by Django 5.2.4 on 2025-07-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_bird_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
